name: tintin_cli
description: Professional Flutter code generator with AI integration
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  dotenv: ^4.2.0
  http: ^1.2.2
  logger: ^2.5.0
  mason: ^0.1.0-dev.57
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  mason_cli: ^0.1.0-dev.55
  test: ^1.24.0
  very_good_analysis: ^5.1.0
